# initialization settings
INITIAL_PLAYER_HEALTH = 5
INITIAL_ENEMY_LEVEL = 1
SCORE_SUCCESS_ATTACK = 10
SCORE_ENEMY_DOWN = 30

# fight choices
WIZARD  = 1
THIEF = 2
KNIGHT = 3
VALID_CHOICES = (WIZARD, THIEF, KNIGHT)

# fight results
SUCCESS = 1
FAILURE = -1
DRAW = 0
